env:
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  {
    '@typescript-eslint/no-empty-function': off,
    no-empty: off,
    '@typescript-eslint/no-explicit-any': off,
    '@typescript-eslint/no-use-before-define': off,
    no-extra-semi: 0,
    object-curly-spacing: [error, never],
    semi: 0,
    space-before-function-paren: 0,
  }
