os: linux
dist: xenial
language: shell
jobs:
  include:
    - language: node_js

      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter

      script:
          - yarn lint
          - yarn prettier
          - yarn prettier-test
          - yarn build
          - ./test_and_report.sh
