mail-familiar:
    persistence:
        password: up
        url: jdbc:sqlite:mailfamiliar.db
        username: whut

spring:
    datasource:
        hikari:
            connection-timeout: 120000
            idle-timeout: 60000
        tomcat:
            max-active: 1

    flyway:
        baseline-on-migrate: true
        enabled: true
        password: ${mail-familiar.persistence.password}
        url: ${mail-familiar.persistence.url}
        user: ${mail-familiar.persistence.username}
